name: Checkout repo
on: workflow_dispatch
    
jobs: 
  files:
    runs-on: ubuntu-latest
    steps:
        - name: printName
          run: |
            echo "Tuomo" > info.txt
            echo "23" > info.txt
            echo "Illman" > info.txt
     
       
      
