name: JobHarjoitus1
on: workflow_dispatch
    
jobs: 
  First:
    runs-on: ubuntu-latest
    steps:
        - name: PrintName
          run: echo "Tuomo" 
  Second:
      needs: First
      runs-on: ubuntu-latest
      steps:
        - name: PrintAge
          run: echo "23"

  Third:
      needs: Second
      runs-on: ubuntu-latest
      steps:
        - name: PrintLname
          run: echo "Illman" >
        
            
            
     
       
      
